---
- name: Update YUM package index
  yum:
    update_cache: yes

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add Docker repository
  yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install Docker
  yum:
    name: docker-ce
    state: present

- name: Start and enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started
